[colors]
foreground = "#c5c2c2"
background = "#190d0b"
cursor_bg = "#4d57aa"
cursor_border = "#6e5eaa"
cursor_fg = "#9f61a4"
selection_bg = "#aa4c7c"
selection_fg = "#aa3f47"
ansi = ["#190d0b","#aa3c2d","#4d57aa","#6e5eaa","#9f61a4","#aa4c7c","#aa3f47","#c5c2c2"]
brights = ["#6e5c5a","#ff5943","#7382ff","#a48dff","#ee91f6","#ff71b9","#ff5e6a","#fffbfb"]
