[package]
name = "dygma_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dygma_focus = "0.4.4"
tokio = { version = "1", features = ["full"] }
